### ISSUE TITLE
Can not open the url of the dataset

### ISSUE THREAD

**Issue by wang149876** [hiker-lw/RealRain-1k#1]
Thank you for your work. I am glad to  see this super-resolution derain dataset. I want to download the dataset from the url that you give but get error. Could you check the url, thank you.

**Comment by hiker-lw** [comment]
Hi,

Thank you for your interest! Could you please try it agian? I can acess the url normally. May be it's the network problem?  If you still cannot open it, feel free to contact us through email [lwzkd@mail.ustc.edu.cn], we are very glad to release the datasets to you for research. Thanks~
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/62053894/223308790-726bfaa8-e182-48d4-8991-ff39a4e892ff.png">

**Comment by wang149876** [comment]
Thank you for your reply. Something went wrong with my network, now I can download the dataset.
